name: Verysimple Demo of CI/CD

on:
  pull_request:
    branches: [master, develop]

jobs:
  demo:
    name: A simple demo job (ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: A simple echo
        run: echo Demo

      - name: Checkout code manually
        run: git clone https://github.com/ngocketit/fs10-githubactions-demo1

      - name: Checkout the code
        uses: actions/checkout@v3

  hello:
    name: A simple hello job (macos)
    runs-on: ubuntu-latest
    steps:
      - name: A simple echo
        run: echo Hello
